### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by flooie** [shamanskyh/Elucidate#1]
I'm in love with this project, and been fooling around with it for an objc version.  I would like to be able to see the full framework and was wondering if you would make that available privately or publicly.  I have some issues with tables that I think I could resolve with more looking at the code.
If not, no worries, thanks for sharing this already.

**Comment by shamanskyh** [comment]
Hi! Sorry I'm just seeing this now, and thanks for your support. The Tesseract Framework in this project is based on another open source project here: https://github.com/gali8/Tesseract-OCR-iOS. They have a Mac implementation on their list of goals, but I was impatient and wanted to tackle it myself. I'm willing to privately share my version if you email me at harry.shamansky@yale.edu, but I suppose a public version should probably be coordinated with the people behind the original iOS version. I considered submitting a pull request on their project, but I'm not sure how they'd like to structure things between Mac and iOS. Hope this is helpful!
